services:
  funny-rater:
    container_name: funny-rater
    image: funny-rater
    develop:
      watch:
        - action: sync
          path: /src
          target: /app
    environment:
      DATABASE_URL: postgres://botrater:supersecret@postgres:5432/botraterdb
      OLLAMA_HOST: host.docker.internal
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: botrater
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: botraterdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U botrater -d botraterdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: